config/routes.rb
Rails.application.routes.draw do
  root to: 'items#index'
  resources :projects
  post "items/filter", to:"items#filter"
  resources :items do
    member do
      get 'toggle'
    end
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :project

  def toggle!
    self.done = !done?
    self.save
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :items

  def done?
    items.all? { |item| item.done? }
  end

  def recent_items
    items.where(created_at: [Time.now.beginning_of_day..Time.now.at_end_of_day])
  end

  def items_by_days
    items.group_by { |item| item.created_at.to_date }
  end

  def to_s
    self.name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy, :toggle]

  def index
    @items = Item.all
  end

  def show
  end

  def new
    @item = Item.new
  end

  def toggle
    @item.toggle!
    respond_to do |format|
      format.js {}
    end
  end

  def filter
    project_id = item_filter_params[:project_id]
    done = item_filter_params[:done]
    @items = project_id.present? ? Item.where(project_id: project_id) : Item.all
    @items = done.present? ? @items.where(done: done) : @items
    respond_to do |format|
      format.js {}
    end
  end

  def edit
  end

  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:description, :done, :project_id)
    end

    def item_filter_params
      params.require(:item_filter).permit(:project_id, :done)
    end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def index
    @projects = Project.all
  end

  def show
  end

  def new
    @project = Project.new
  end

  def edit
  end

  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for(@item) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :done %><br>
    <%= f.check_box :done %>
  </div>
  <div class="field">
    <%= f.label :project %><br>
    <%= f.collection_select(:project_id, Project.all, :id, :name, :include_blank => "Please select") %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/_index_rows.html.erb
<% items.each do |item| %>
  <tr id="item_<%= item.id %>"><%= render partial: "item_row", locals: { item: item } %></tr>
<% end %>

app/views/items/_item_row.html.erb
<td><%= item.description %></td>
<td><%= item.done %></td>
<td><%= item.project %></td>
<td><%= link_to 'Show', item %></td>
<td><%= link_to 'Edit', edit_item_path(item) %></td>
<td><%= render partial: 'toggle', locals: { item: item } %></td>
<td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>

app/views/items/_toggle.html.erb
<% if item.done? %>
  <%= link_to 'Open', toggle_item_path(item), remote: true %>
<% else %>
  <%= link_to 'Close', toggle_item_path(item), remote: true %>
<% end %>

app/views/items/edit.html.erb
<h1>Editing item</h1>

<%= render 'form' %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/filter.js.erb
$("#index_rows_container").html("<%= escape_javascript(render partial: "index_rows", locals: { items: @items }) %>");

app/views/items/index.html.erb
<h1>Listing items</h1>

<%= form_for :item_filter, url: items_filter_path, remote:true do |f| %>
  <p> Filter by: </p>
  <div class="field">
    <%= f.label :project %><br>
    <%= f.collection_select(:project_id, Project.all, :id, :name, :include_blank => "Please select") %>
  </div>
  <div class="field">
    <%= f.label :done %><br>
    <%= f.collection_select(:done, [[1, 'True'], [0, "False"]], :first, :last, :include_blank => "All") %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Done</th>
      <th>Project</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody id="index_rows_container"><%= render partial: "index_rows", locals: { items: @items }%></tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>
<%= link_to 'Projects', projects_path %>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Done:</strong>
  <%= @item.done %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/items/toggle.js.erb
$("#item_<%= @item.id %>").html("<%= escape_javascript(render partial: "item_row", locals: { item: @item }) %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodoList</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name%>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/_toggle.html.erb
<% if item.done? %>
  <%= link_to 'Open', toggle_item_path(item), remote: true %>
<% else %>
  <%= link_to 'Close', toggle_item_path(item), remote: true %>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Listing projects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name%></td>
        <td><%= project.description%></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New project', new_project_path %>
<%= link_to 'Items', items_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name%>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/projects/toggle.js.erb
$("#open_close_item_<%= @item.id %>").html("<%= escape_javascript(render partial: "toggle", locals: { item: @item }) %>");